import { Metadata } from 'next'
import { Phone, Mail, MapPin, Clock, MessageCircle } from 'lucide-react'
import { siteConfig } from '@/data/site'
import { FadeIn } from '@/components/FadeIn'
import { ContactForm } from '@/components/ContactForm'
export const metadata: Metadata = { title: 'Contacto', description: 'Contacta con Inmobiliaria Elite Bienes de Patrimonio.' }
export default function ContactoPage() { const waPhone = siteConfig.phone.replace(/[^0-9]/g,''); return (<>
  <section className="relative pt-32 pb-16 lg:pt-40 lg:pb-20"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1920&q=80" alt="Contacto" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-brand-navy/80"/></div><div className="relative z-10 section-padding"><div className="container-elite max-w-3xl"><FadeIn><span className="text-brand-gold text-xs font-semibold uppercase tracking-[0.25em]">Contacto</span></FadeIn><FadeIn delay={0.1}><h1 className="heading-xl text-white mt-4 mb-6">Estamos aquí para ayudarte</h1></FadeIn></div></div></section>
  <section className="bg-white py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><div className="grid grid-cols-1 lg:grid-cols-5 gap-12 lg:gap-16"><div className="lg:col-span-2"><FadeIn><h2 className="heading-md mb-8">Información de contacto</h2><div className="space-y-6"><a href={`tel:${siteConfig.phone}`} className="flex items-start gap-4 group hover:text-brand-gold"><div className="w-12 h-12 bg-brand-gold/10 rounded-sm flex items-center justify-center"><Phone size={20} className="text-brand-gold"/></div><div><p className="text-xs text-brand-warm-gray uppercase tracking-wider mb-1">Teléfono</p><p className="font-display text-xl font-semibold text-brand-navy">{siteConfig.phoneDisplay}</p></div></a><a href={`mailto:${siteConfig.email}`} className="flex items-start gap-4 group hover:text-brand-gold"><div className="w-12 h-12 bg-brand-gold/10 rounded-sm flex items-center justify-center"><Mail size={20} className="text-brand-gold"/></div><div><p className="text-xs text-brand-warm-gray uppercase tracking-wider mb-1">Email</p><p className="text-brand-navy font-medium">{siteConfig.email}</p></div></a><div className="flex items-start gap-4"><div className="w-12 h-12 bg-brand-gold/10 rounded-sm flex items-center justify-center"><MapPin size={20} className="text-brand-gold"/></div><div><p className="text-xs text-brand-warm-gray uppercase tracking-wider mb-1">Dirección</p><p className="text-brand-charcoal text-sm">{siteConfig.address.street}<br/>{siteConfig.address.postalCode} {siteConfig.address.city}</p></div></div><div className="flex items-start gap-4"><div className="w-12 h-12 bg-brand-gold/10 rounded-sm flex items-center justify-center"><Clock size={20} className="text-brand-gold"/></div><div><p className="text-xs text-brand-warm-gray uppercase tracking-wider mb-1">Horario</p><p className="text-brand-charcoal text-sm">{siteConfig.hours.weekdays}<br/>{siteConfig.hours.saturday}</p></div></div></div></FadeIn></div><div className="lg:col-span-3"><FadeIn delay={0.2} direction="left"><div className="bg-brand-light-bg p-8 lg:p-10 rounded-sm"><ContactForm variant="general"/></div></FadeIn></div></div></div></div></section>
</>)}
