import { Metadata } from 'next'
import Link from 'next/link'
import { Phone, ArrowRight, Star, Shield, Users, Heart, MapPin, Target, Eye } from 'lucide-react'
import { siteConfig, testimonials } from '@/data/site'
import { FadeIn, StaggerContainer, StaggerItem } from '@/components/FadeIn'
import { SectionHeading } from '@/components/SectionHeading'
export const metadata: Metadata = { title: 'Sobre nosotros', description: 'Conoce al equipo de Inmobiliaria \u00c9lite.' }
export default function NosotrosPage() { return (<>
  <section className="relative pt-32 pb-20 lg:pt-40 lg:pb-28"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1920&q=80" alt="Equipo" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-brand-navy/80"/></div><div className="relative z-10 section-padding"><div className="container-elite max-w-3xl"><FadeIn><span className="text-brand-gold text-xs font-semibold uppercase tracking-[0.25em]">Sobre nosotros</span></FadeIn><FadeIn delay={0.1}><h1 className="heading-xl text-white mt-4 mb-6">Un equipo que conoce tu tierra</h1></FadeIn><FadeIn delay={0.2}><p className="text-lg text-white/80 leading-relaxed max-w-xl">Somos un equipo joven, profesional y comprometido con ofrecer el mejor servicio inmobiliario en el Levante Almeriense.</p></FadeIn></div></div></section>
  <section className="bg-white py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20 items-center"><FadeIn><div><span className="text-brand-gold text-xs font-semibold uppercase tracking-[0.25em]">Nuestra historia</span><h2 className="heading-lg mt-3 mb-6">Nacidos en esta tierra, comprometidos contigo</h2><div className="space-y-4 text-body"><p>Inmobiliaria \u00c9lite nace de la convicci\u00f3n de que el sector inmobiliario necesita un enfoque m\u00e1s humano, transparente y profesional. Desde Hu\u00e9rcal-Overa, ponemos al servicio de nuestros clientes todo nuestro conocimiento del mercado local.</p><p>Nuestro equipo combina la energ\u00eda de una generaci\u00f3n joven con el rigor que requiere una operaci\u00f3n inmobiliaria.</p><p>Cada persona que entra por nuestra puerta recibe un trato personalizado, informaci\u00f3n clara y honesta, y el acompa\u00f1amiento completo que merece.</p></div></div></FadeIn><FadeIn delay={0.2} direction="left"><div className="relative"><img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80" alt="Oficina" className="rounded-sm shadow-xl"/></div></FadeIn></div></div></div></section>
  <section className="bg-brand-light-bg py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><SectionHeading label="Valores" title="Lo que nos define"/><StaggerContainer className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{[{i:Shield,t:'Transparencia',d:'Informaci\u00f3n clara desde el primer momento.'},{i:Heart,t:'Cercan\u00eda',d:'Nos tomamos el tiempo de escucharte.'},{i:Target,t:'Profesionalidad',d:'Formaci\u00f3n continua y procesos rigurosos.'},{i:MapPin,t:'Conocimiento local',d:'Vivimos y trabajamos en el Levante Almeriense.'},{i:Users,t:'Compromiso',d:'No paramos hasta que consigues tu objetivo.'},{i:Eye,t:'Honestidad',d:'Nuestra reputaci\u00f3n va primero.'}].map(({i:I,t,d})=><StaggerItem key={t}><div className="card-elite p-8 h-full"><I size={28} className="text-brand-gold mb-4"/><h3 className="font-display text-xl font-semibold text-brand-navy mb-3">{t}</h3><p className="text-sm text-brand-slate leading-relaxed">{d}</p></div></StaggerItem>)}</StaggerContainer></div></div></section>
  <section className="bg-brand-cream py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><SectionHeading label="Opiniones" title="La confianza se gana con hechos"/><StaggerContainer className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">{testimonials.slice(0,4).map((t,i)=><StaggerItem key={i}><div className="bg-white p-8 rounded-sm shadow-sm"><div className="flex mb-4">{[...Array(t.rating)].map((_,j)=><Star key={j} size={16} className="text-brand-gold fill-brand-gold"/>)}</div><p className="text-brand-slate leading-relaxed mb-4">&ldquo;{t.text}&rdquo;</p><span className="font-display font-semibold text-brand-navy">{t.author}</span></div></StaggerItem>)}</StaggerContainer></div></div></section>
  <section className="bg-white py-16 lg:py-24"><div className="section-padding"><div className="container-elite text-center"><FadeIn><h2 className="heading-lg mb-4">\u00bfQuieres conocernos?</h2><p className="text-body text-lg max-w-lg mx-auto mb-10">Vis\u00edtanos o ll\u00e1manos. La primera consulta es gratuita.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/contacto" className="btn-primary">Contactar<ArrowRight size={16}/></Link><a href={`tel:${siteConfig.phone}`} className="btn-secondary"><Phone size={16}/>{siteConfig.phoneDisplay}</a></div></FadeIn></div></div></section>
</>)}
