import { Metadata } from 'next'
import Link from 'next/link'
import { Phone, ArrowRight, CheckCircle, TrendingUp, Camera, Globe, Users } from 'lucide-react'
import { siteConfig, sellingSteps } from '@/data/site'
import { FadeIn, StaggerContainer, StaggerItem } from '@/components/FadeIn'
import { SectionHeading } from '@/components/SectionHeading'
import { ContactForm } from '@/components/ContactForm'
export const metadata: Metadata = { title: 'Vender propiedad en Hu\u00e9rcal-Overa', description: 'Vende tu vivienda al mejor precio.' }
export default function VenderPage() { return (<>
  <section className="relative pt-32 pb-20 lg:pt-40 lg:pb-28"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80" alt="Interior vivienda" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-brand-navy/80"/></div><div className="relative z-10 section-padding"><div className="container-elite max-w-3xl"><FadeIn><span className="text-brand-gold text-xs font-semibold uppercase tracking-[0.25em]">Vender propiedad</span></FadeIn><FadeIn delay={0.1}><h1 className="heading-xl text-white mt-4 mb-6">Vende tu propiedad al mejor precio</h1></FadeIn><FadeIn delay={0.2}><p className="text-lg text-white/80 max-w-xl">Estrategia de venta personalizada. Valoraci\u00f3n gratuita.</p></FadeIn><FadeIn delay={0.3}><div className="flex flex-col sm:flex-row gap-4 mt-8"><a href="#valoracion" className="btn-primary text-base py-4 px-8">Solicitar valoraci\u00f3n<ArrowRight size={18}/></a><a href={`tel:${siteConfig.phone}`} className="btn-outline-gold text-base py-4 px-8"><Phone size={18}/>{siteConfig.phoneDisplay}</a></div></FadeIn></div></div></section>
  <section className="bg-white py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><SectionHeading label="Nuestro compromiso" title="Lo que hacemos por ti como propietario"/><StaggerContainer className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">{[{i:TrendingUp,t:'Valoraci\u00f3n profesional',d:'Precio competitivo basado en datos reales'},{i:Camera,t:'Fotograf\u00eda profesional',d:'Presentaci\u00f3n atractiva de tu inmueble'},{i:Globe,t:'Difusi\u00f3n multicanal',d:'Portales l\u00edderes y redes sociales'},{i:Users,t:'Gesti\u00f3n integral',d:'Filtramos compradores y gestionamos todo'}].map(({i:I,t,d})=><StaggerItem key={t}><div className="card-elite p-8 h-full text-center"><div className="w-14 h-14 bg-brand-gold/10 rounded-full flex items-center justify-center mx-auto mb-5"><I size={24} className="text-brand-gold"/></div><h3 className="font-display text-lg font-semibold text-brand-navy mb-3">{t}</h3><p className="text-sm text-brand-slate leading-relaxed">{d}</p></div></StaggerItem>)}</StaggerContainer></div></div></section>
  <section className="bg-brand-light-bg py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><SectionHeading label="Proceso de venta" title="As\u00ed vendemos tu propiedad"/><div className="max-w-4xl mx-auto"><StaggerContainer className="space-y-10">{sellingSteps.map(s=><StaggerItem key={s.step}><div className="flex gap-6 md:gap-8"><div className="flex-shrink-0 w-12 h-12 bg-brand-gold text-white rounded-full flex items-center justify-center font-display font-bold text-lg">{s.step}</div><div className="pt-1"><h3 className="font-display text-xl font-semibold text-brand-navy mb-2">{s.title}</h3><p className="text-body">{s.description}</p></div></div></StaggerItem>)}</StaggerContainer></div></div></div></section>
  <section id="valoracion" className="bg-brand-cream py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20"><div><SectionHeading label="Valoraci\u00f3n gratuita" title="Descubre cu\u00e1nto vale tu propiedad" centered={false}/></div><FadeIn delay={0.2} direction="left"><div className="bg-white p-8 lg:p-10 rounded-sm shadow-sm border border-gray-100"><ContactForm variant="vender"/></div></FadeIn></div></div></div></section>
</>)}
