import { Metadata } from 'next'
import Link from 'next/link'
import { Phone, ArrowRight, Star, Shield, Users, TrendingUp, MapPin, Home, Search, Calculator, CheckCircle, Quote, ChevronRight } from 'lucide-react'
import { siteConfig, testimonials, featuredProperties, services } from '@/data/site'
import { FadeIn, StaggerContainer, StaggerItem } from '@/components/FadeIn'
import { SectionHeading } from '@/components/SectionHeading'
import { PropertyCard } from '@/components/PropertyCard'
import { ContactForm } from '@/components/ContactForm'

export const metadata: Metadata = { title: 'Inmobiliaria \u00c9lite | Compra y venta de viviendas en Hu\u00e9rcal-Overa, Almer\u00eda', description: 'Tu inmobiliaria de confianza en Hu\u00e9rcal-Overa.' }

export default function HomePage() {
  return (<>
    <section className="relative min-h-screen flex items-center"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80" alt="Vivienda premium" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-brand-navy/90 via-brand-navy/70 to-brand-navy/40"/></div>
      <div className="relative z-10 section-padding w-full pt-32 pb-20"><div className="container-elite"><div className="max-w-2xl">
        <FadeIn><span className="inline-block text-brand-gold text-xs font-semibold uppercase tracking-[0.25em] mb-6 border border-brand-gold/30 px-4 py-2">Inmobiliaria en Hu\u00e9rcal-Overa</span></FadeIn>
        <FadeIn delay={0.15}><h1 className="font-display text-4xl sm:text-5xl lg:text-6xl xl:text-7xl font-bold text-white leading-[1.1] mb-6">Tu hogar ideal en el <span className="text-brand-gold">Levante Almeriense</span></h1></FadeIn>
        <FadeIn delay={0.3}><p className="text-lg lg:text-xl text-white/80 leading-relaxed mb-10 max-w-xl">Compra, vende o invierte con la tranquilidad de un equipo que conoce cada rinc\u00f3n de esta tierra.</p></FadeIn>
        <FadeIn delay={0.45}><div className="flex flex-col sm:flex-row gap-4"><Link href="/comprar" className="btn-primary text-base py-4 px-8">Busco vivienda<ArrowRight size={18}/></Link><Link href="/vender" className="btn-outline-gold text-base py-4 px-8">Quiero vender</Link></div></FadeIn>
      </div></div></div>
    </section>
    <section className="bg-white border-b border-gray-100"><div className="section-padding py-8 lg:py-10"><div className="container-elite"><StaggerContainer className="grid grid-cols-2 lg:grid-cols-4 gap-8 text-center">{[{v:'4,8/5',l:'Google',i:Star},{v:'100+',l:'Familias',i:Users},{v:'100%',l:'Compromiso',i:Shield},{v:'10+',l:'Zonas',i:MapPin}].map(({v,l,i:I})=><StaggerItem key={l}><div className="flex flex-col items-center"><I size={22} className="text-brand-gold mb-2"/><span className="font-display text-2xl lg:text-3xl font-bold text-brand-navy">{v}</span><span className="text-xs text-brand-warm-gray uppercase tracking-wider mt-1">{l}</span></div></StaggerItem>)}</StaggerContainer></div></div></section>
    <section className="bg-brand-light-bg py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><SectionHeading label="Nuestros servicios" title="Todo lo que necesitas, en un solo lugar" description="Servicio integral para comprar, vender o invertir en el Levante Almeriense."/><StaggerContainer className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{services.slice(0,6).map(s=><StaggerItem key={s.id}><div className="card-elite p-8 h-full"><h3 className="font-display text-lg font-semibold text-brand-navy mb-3">{s.title}</h3><p className="text-sm text-brand-slate leading-relaxed">{s.description}</p></div></StaggerItem>)}</StaggerContainer><FadeIn delay={0.3}><div className="text-center mt-10"><Link href="/servicios" className="btn-secondary">Ver todos los servicios<ChevronRight size={16}/></Link></div></FadeIn></div></div></section>
    <section className="bg-white py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><SectionHeading label="Propiedades destacadas" title="Encuentra tu pr\u00f3ximo hogar"/><StaggerContainer className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{featuredProperties.slice(0,3).map(p=><StaggerItem key={p.id}><PropertyCard {...p}/></StaggerItem>)}</StaggerContainer><FadeIn delay={0.3}><div className="text-center mt-10"><Link href="/comprar" className="btn-primary">Ver m\u00e1s propiedades<ArrowRight size={16}/></Link></div></FadeIn></div></div></section>
    <section className="bg-brand-cream py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><SectionHeading label="Opiniones" title="Lo que dicen nuestros clientes"/><StaggerContainer className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">{testimonials.map((t,i)=><StaggerItem key={i}><div className="bg-white p-6 rounded-sm shadow-sm h-full flex flex-col"><Quote size={24} className="text-brand-gold/30 mb-4"/><p className="text-sm text-brand-slate leading-relaxed flex-1 mb-4">&ldquo;{t.text}&rdquo;</p><div className="flex items-center justify-between border-t border-gray-100 pt-4"><span className="font-medium text-sm text-brand-navy">{t.author}</span><div className="flex">{[...Array(t.rating)].map((_,j)=><Star key={j} size={12} className="text-brand-gold fill-brand-gold"/>)}</div></div></div></StaggerItem>)}</StaggerContainer></div></div></section>
    <section className="bg-brand-light-bg py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-20"><div><SectionHeading label="Contacto" title="Hablemos de tu proyecto" description="Cu\u00e9ntanos qu\u00e9 necesitas." centered={false}/></div><FadeIn delay={0.2} direction="left"><div className="bg-white p-8 lg:p-10 rounded-sm shadow-sm border border-gray-100"><ContactForm variant="general"/></div></FadeIn></div></div></div></section>
  </>)
}
