import { Metadata } from 'next'
import Link from 'next/link'
import { Home, Search, Calculator, TrendingUp, Users, Shield, ArrowRight, Phone, CheckCircle } from 'lucide-react'
import { siteConfig } from '@/data/site'
import { FadeIn, StaggerContainer, StaggerItem } from '@/components/FadeIn'
import { SectionHeading } from '@/components/SectionHeading'
export const metadata: Metadata = { title: 'Servicios inmobiliarios en Hu\u00e9rcal-Overa', description: 'Servicios inmobiliarios completos.' }
const allServices = [{icon:Home,title:'Compra y venta de inmuebles',desc:'Te acompa\u00f1amos en cada paso del proceso.',details:['B\u00fasqueda personalizada','Negociaci\u00f3n profesional','Verificaci\u00f3n legal','Coordinaci\u00f3n con notar\u00edas','Gesti\u00f3n integral']},{icon:Search,title:'Captaci\u00f3n de inmuebles',desc:'Conectamos propietarios con compradores.',details:['Prospecci\u00f3n activa','Red de contactos','Base de datos activa']},{icon:Calculator,title:'Asesoramiento financiero',desc:'Mejores condiciones hipotecarias.',details:['Estudio de viabilidad','Comparativa de ofertas','Negociaci\u00f3n bancaria']},{icon:TrendingUp,title:'Valoraci\u00f3n profesional',desc:'Datos reales del mercado local.',details:['An\u00e1lisis comparativo','Informe detallado','Recomendaciones']},{icon:Users,title:'Estrategia de comercializaci\u00f3n',desc:'Planes de marketing personalizados.',details:['Fotograf\u00eda profesional','Portales l\u00edderes','Redes sociales']},{icon:Shield,title:'Acompa\u00f1amiento integral',desc:'Desde consulta hasta notar\u00eda.',details:['Asesor\u00eda personalizada','Gesti\u00f3n documental','Servicio postventa']}]
export default function ServiciosPage() { return (<>
  <section className="relative pt-32 pb-20 lg:pt-40 lg:pb-28"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1920&q=80" alt="Servicios" className="w-full h-full object-cover"/><div className="absolute inset-0 bg-brand-navy/80"/></div><div className="relative z-10 section-padding"><div className="container-elite max-w-3xl"><FadeIn><span className="text-brand-gold text-xs font-semibold uppercase tracking-[0.25em]">Servicios</span></FadeIn><FadeIn delay={0.1}><h1 className="heading-xl text-white mt-4 mb-6">Servicios inmobiliarios completos</h1></FadeIn><FadeIn delay={0.2}><p className="text-lg text-white/80 max-w-xl">Un servicio integral para comprar, vender o invertir de forma segura.</p></FadeIn></div></div></section>
  <section className="bg-white py-20 lg:py-28"><div className="section-padding"><div className="container-elite"><div className="space-y-16">{allServices.map((s,i)=>{const I=s.icon;return(<FadeIn key={s.title} delay={0.1}><div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-16 items-start"><div className={i%2!==0?'lg:order-2':''}><div className="flex items-center gap-4 mb-4"><div className="w-12 h-12 bg-brand-gold/10 rounded-sm flex items-center justify-center"><I size={24} className="text-brand-gold"/></div><h2 className="heading-sm">{s.title}</h2></div><p className="text-body text-lg mb-6">{s.desc}</p></div><div className={i%2!==0?'lg:order-1':''}><div className="bg-brand-light-bg p-6 lg:p-8 rounded-sm"><h4 className="text-sm font-semibold uppercase tracking-wider text-brand-gold mb-4">Incluye</h4><div className="space-y-3">{s.details.map(d=><div key={d} className="flex items-start gap-3"><CheckCircle size={16} className="text-brand-gold flex-shrink-0 mt-0.5"/><span className="text-sm text-brand-charcoal">{d}</span></div>)}</div></div></div></div>{i<allServices.length-1&&<div className="border-b border-gray-100 mt-16"/>}</FadeIn>)})}</div></div></div></section>
  <section className="bg-brand-navy py-16 lg:py-24"><div className="section-padding"><div className="container-elite text-center"><FadeIn><span className="text-brand-gold text-xs font-semibold uppercase tracking-[0.25em]">\u00bfHablamos?</span><h2 className="heading-lg text-white mt-4 mb-6">\u00bfNecesitas alguno de estos servicios?</h2><p className="text-lg text-white/70 max-w-lg mx-auto mb-10">Cu\u00e9ntanos tu situaci\u00f3n. La primera consulta es gratuita.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/contacto" className="btn-primary text-base py-4 px-8">Contactar<ArrowRight size={18}/></Link><a href={`tel:${siteConfig.phone}`} className="btn-outline-gold text-base py-4 px-8"><Phone size={18}/>{siteConfig.phoneDisplay}</a></div></FadeIn></div></div></section>
</>)}
